## 1.1. Import library pandas beri nama pd
## 1.2. Baca data file nba terlampir simpan dengan nama dataku
## 1.3. Tampilkan isi dataku

In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd
import numpy as np

#importing the dataset 
df = pd.read_excel('datagaji.xlsx')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NEGARA  10 non-null     object
 1   USIA    9 non-null      float64
 2   GAJI    9 non-null      float64
 3   BELI    10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

In [3]:
dfupdatena = df.copy()
dfupdatena.head

<bound method NDFrame.head of     NEGARA  USIA     GAJI BELI
0   France  44.0  58000.0   No
1    Spain  27.0  48000.0  Yes
2  Germany   NaN  64000.0   No
3    Spain  35.0  62000.0  Yes
4  Germany  40.0  54000.0  Yes
5   France  35.0      NaN  Yes
6    Spain  38.0  52000.0   No
7   France  48.0  79000.0  Yes
8  Germany  55.0  83000.0   No
9   France  32.0  68000.0  Yes>

In [4]:
dfupdatena['USIA']= dfupdatena['USIA'].fillna(dfupdatena['USIA'].mean())
dfupdatena.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NEGARA  10 non-null     object
 1   USIA    10 non-null     float64
 2   GAJI    9 non-null      float64
 3   BELI    10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

In [5]:
dfupdatena.head

<bound method NDFrame.head of     NEGARA       USIA     GAJI BELI
0   France  44.000000  58000.0   No
1    Spain  27.000000  48000.0  Yes
2  Germany  39.333333  64000.0   No
3    Spain  35.000000  62000.0  Yes
4  Germany  40.000000  54000.0  Yes
5   France  35.000000      NaN  Yes
6    Spain  38.000000  52000.0   No
7   France  48.000000  79000.0  Yes
8  Germany  55.000000  83000.0   No
9   France  32.000000  68000.0  Yes>

In [6]:
dfupdatena['GAJI'] = dfupdatena['GAJI'].fillna(dfupdatena['GAJI'].mean())
dfupdatena.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NEGARA  10 non-null     object
 1   USIA    10 non-null     float64
 2   GAJI    10 non-null     float64
 3   BELI    10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

In [7]:
dfupdatena

    NEGARA       USIA          GAJI BELI
0   France  44.000000  58000.000000   No
1    Spain  27.000000  48000.000000  Yes
2  Germany  39.333333  64000.000000   No
3    Spain  35.000000  62000.000000  Yes
4  Germany  40.000000  54000.000000  Yes
5   France  35.000000  63111.111111  Yes
6    Spain  38.000000  52000.000000   No
7   France  48.000000  79000.000000  Yes
8  Germany  55.000000  83000.000000   No
9   France  32.000000  68000.000000  Yes

In [8]:
dfupdatena.describe()

            USIA          GAJI
count  10.000000     10.000000
mean   39.333333  63111.111111
std     8.082904  11229.370661
min    27.000000  48000.000000
25%    35.000000  55000.000000
50%    38.666667  62555.555556
75%    43.000000  67000.000000
max    55.000000  83000.000000

In [9]:
dfupdatezscore = dfupdatena.copy()
dfupdatezscore

    NEGARA       USIA          GAJI BELI
0   France  44.000000  58000.000000   No
1    Spain  27.000000  48000.000000  Yes
2  Germany  39.333333  64000.000000   No
3    Spain  35.000000  62000.000000  Yes
4  Germany  40.000000  54000.000000  Yes
5   France  35.000000  63111.111111  Yes
6    Spain  38.000000  52000.000000   No
7   France  48.000000  79000.000000  Yes
8  Germany  55.000000  83000.000000   No
9   France  32.000000  68000.000000  Yes

In [10]:
dfupdatezscore.drop("NEGARA",axis=1,inplace=True)
dfupdatezscore.drop("BELI",axis=1,inplace=True)

In [11]:
dfupdatezscore

        USIA          GAJI
0  44.000000  58000.000000
1  27.000000  48000.000000
2  39.333333  64000.000000
3  35.000000  62000.000000
4  40.000000  54000.000000
5  35.000000  63111.111111
6  38.000000  52000.000000
7  48.000000  79000.000000
8  55.000000  83000.000000
9  32.000000  68000.000000

In [12]:
x = dfupdatena[['USIA', 'GAJI']]
x

        USIA          GAJI
0  44.000000  58000.000000
1  27.000000  48000.000000
2  39.333333  64000.000000
3  35.000000  62000.000000
4  40.000000  54000.000000
5  35.000000  63111.111111
6  38.000000  52000.000000
7  48.000000  79000.000000
8  55.000000  83000.000000
9  32.000000  68000.000000

In [13]:
from sklearn.preprocessing import StandardScaler

ss =StandardScaler()
zscore_df = ss.fit_transform(dfupdatezscore)

In [14]:
zscore_df

array([[ 0.60858062, -0.47977614],
       [-1.60839164, -1.4184686 ],
       [ 0.        ,  0.08343933],
       [-0.56511058, -0.10429916],
       [ 0.08694009, -0.85525313],
       [-0.56511058,  0.        ],
       [-0.17388018, -1.04299162],
       [ 1.13022115,  1.49147801],
       [ 2.04309208,  1.866955  ],
       [-0.95634097,  0.45891631]])

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_minmax = scaler.fit_transform(dfupdatezscore)
x_minmax

array([[0.60714286, 0.28571429],
       [0.        , 0.        ],
       [0.44047619, 0.45714286],
       [0.28571429, 0.4       ],
       [0.46428571, 0.17142857],
       [0.28571429, 0.43174603],
       [0.39285714, 0.11428571],
       [0.75      , 0.88571429],
       [1.        , 1.        ],
       [0.17857143, 0.57142857]])

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler2 = MinMaxScaler(feature_range=(1,10))
x_minmax2 = scaler2.fit_transform(dfupdatezscore)
x_minmax2

array([[ 6.46428571,  3.57142857],
       [ 1.        ,  1.        ],
       [ 4.96428571,  5.11428571],
       [ 3.57142857,  4.6       ],
       [ 5.17857143,  2.54285714],
       [ 3.57142857,  4.88571429],
       [ 4.53571429,  2.02857143],
       [ 7.75      ,  8.97142857],
       [10.        , 10.        ],
       [ 2.60714286,  6.14285714]])

In [17]:
df_minmax2 = pd.DataFrame(x_minmax2, columns=['MinMax10_USIA','MinMax10_GAJI' ])
df_minmax2

   MinMax10_USIA  MinMax10_GAJI
0       6.464286       3.571429
1       1.000000       1.000000
2       4.964286       5.114286
3       3.571429       4.600000
4       5.178571       2.542857
5       3.571429       4.885714
6       4.535714       2.028571
7       7.750000       8.971429
8      10.000000      10.000000
9       2.607143       6.142857

In [18]:
concatenated3 = pd.concat([dfupdatena, df_minmax2], axis="columns")
concatenated3

    NEGARA       USIA          GAJI BELI  MinMax10_USIA  MinMax10_GAJI
0   France  44.000000  58000.000000   No       6.464286       3.571429
1    Spain  27.000000  48000.000000  Yes       1.000000       1.000000
2  Germany  39.333333  64000.000000   No       4.964286       5.114286
3    Spain  35.000000  62000.000000  Yes       3.571429       4.600000
4  Germany  40.000000  54000.000000  Yes       5.178571       2.542857
5   France  35.000000  63111.111111  Yes       3.571429       4.885714
6    Spain  38.000000  52000.000000   No       4.535714       2.028571
7   France  48.000000  79000.000000  Yes       7.750000       8.971429
8  Germany  55.000000  83000.000000   No      10.000000      10.000000
9   France  32.000000  68000.000000  Yes       2.607143       6.142857

In [19]:
df_zscore=pd.DataFrame(zscore_df, columns=['ZSCORE_USIA', 'ZSCORE_GAJI'])
df_minmax1 = pd.DataFrame(x_minmax, columns=['MinMax01_USIA', 'MinMax01_GAJI'])
df_minmax2 = pd.DataFrame(x_minmax2, columns=['MinMax10_USIA', 'MinMax10_GAJI'])

In [20]:
gabung_all=pd.concat([dfupdatena,df_zscore,df_minmax2,df_minmax1], axis="columns")
gabung_all

,NEGARA,USIA,GAJI,BELI,ZSCORE_USIA,ZSCORE_GAJI,MinMax10_USIA,MinMax10_GAJI,MinMax01_USIA,MinMax01_GAJI
0,France,44.000000,58000.000000,No,0.608581,-0.479776,6.464286,3.571429,0.607143,0.285714
1,Spain,27.000000,48000.000000,Yes,-1.608392,-1.418469,1.000000,1.000000,0.000000,0.000000
2,Germany,39.333333,64000.000000,No,0.000000,0.083439,4.964286,5.114286,0.440476,0.457143
3,Spain,35.000000,62000.000000,Yes,-0.565111,-0.104299,3.571429,4.600000,0.285714,0.400000
4,Germany,40.000000,54000.000000,Yes,0.086940,-0.855253,5.178571,2.542857,0.464286,0.171429
5,France,35.000000,63111.111111,Yes,-0.565111,0.000000,3.571429,4.885714,0.285714,0.431746
6,Spain,38.000000,52000.000000,No,-0.173880,-1.042992,4.535714,2.028571,0.392857,0.114286
7,France,48.000000,79000.000000,Yes,1.130221,1.491478,7.750000,8.971429,0.750000,0.885714
8,Germany,55.000000,83000.000000,No,2.043092,1.866955,10.000000,10.000000,1.000000,1.000000
9,France,32.000000,68000.000000,Yes,-0.956341,0.458916,2.607143,6.142857,0.178571,0.571429

In [21]:
gabung_all.to_excel("hasil_daftargaji_.xlsx")