In [2]:
## 1.1. Import library pandas beri nama pd
import pandas as pd
## 1.2. Baca data file nba terlampir simpan dengan nama dataku
dataku=pd.read_csv("nba.csv")
## 1.3. Tampilkan isi dataku
dataku

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
dataku.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [4]:
dataku.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#Deskripsi statistik untuk data numerik
dataku.describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [6]:
dataku.shape

(458, 9)

In [7]:
print(dataku.isnull().sum())

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

2.2. Berbagai Cara Penanganan Missing Value

2.2.1. Menghapus kolom yang memiliki missing value

In [8]:
datakuhapuskolom = dataku.dropna(axis=1)
datakuhapuskolom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Empty DataFrame

In [9]:
datakuhapusbaris = dataku.dropna(axis=0)
datakuhapusbaris.info()

<class 'pandas.core.frame.DataFrame'>
Index: 364 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      364 non-null    object
 1   Team      364 non-null    object
 2   Number    364 non-null    float64
 3   Position  364 non-null    object
 4   Age       364 non-null    float64
 5   Height    364 non-null    object
 6   Weight    364 non-null    float64
 7   College   364 non-null    object
 8   Salary    364 non-null    float64
dtypes: float64(4), object(5)
memory usage: 28.4+ KB

In [10]:
dfupdatena=dataku.copy()

In [11]:
dfupdatena.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [12]:
print(dfupdatena.isnull().sum())

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [13]:
dfupdatena['Salary']= dfupdatena['Salary'].fillna(dfupdatena['Salary']).mean()

In [14]:
print(dfupdatena.isnull().sum())

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary       0
dtype: int64

In [15]:
updated_df = dataku
updated_df['Salarymissing'] = updated_df['Salary'].isnull()
updated_df['Collegemissing']=updated_df['College'].isnull()
from sklearn.impute import SimpleImputer
kolom_numerik = updated_df.select_dtypes(include=['float64', 'int64']).columns
my_imputer = SimpleImputer(strategy = 'median')
updated_df[kolom_numerik] = my_imputer.fit_transform(updated_df[kolom_numerik])
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            457 non-null    object
 1   Team            457 non-null    object
 2   Number          458 non-null    float64
 3   Position        457 non-null    object
 4   Age             458 non-null    float64
 5   Height          457 non-null    object
 6   Weight          458 non-null    float64
 7   College         373 non-null    object
 8   Salary          458 non-null    float64
 9   Salarymissing   458 non-null    bool
 10  Collegemissing  458 non-null    bool
dtypes: bool(2), float64(4), object(5)
memory usage: 33.2+ KB

In [18]:
updated_df.head()
updated_df.to_excel("hasil_datacollection_.xlsx")

In [17]:
print(updated_df.isnull().sum())
print(updated_df.isnull().sum)

Name               1
Team               1
Number             0
Position           1
Age                0
Height             1
Weight             0
College           85
Salary             0
Salarymissing      0
Collegemissing     0
dtype: int64
<bound method DataFrame.sum of       Name   Team  Number  Position    Age  Height  Weight  College  Salary  \
0    False  False   False     False  False   False   False    False   False
1    False  False   False     False  False   False   False    False   False
2    False  False   False     False  False   False   False    False   False
3    False  False   False     False  False   False   False    False   False
4    False  False   False     False  False   False   False     True   False
..     ...    ...     ...       ...    ...     ...     ...      ...     ...
453  False  False   False     False  False   False   False    False   False
454  False  False   False     False  False   False   False     True   False
455  False  False   False     False  False   False   False     True   False
456  False  False   False     False  False   False   False    False   False
457   True   True   False      True  False    True   False     True   False

     Salarymissing  Collegemissing
0            False           False
1            False           False
2            False           False
3            False           False
4            False           False
..             ...             ...
453          False           False
454          False           False
455          False           False
456          False           False
457          False           False

[458 rows x 11 columns]>